server.port: 9000

spring:
  datasource:
    url: "jdbc:postgresql://localhost/emzo"
    username: postgres
    password: postgres
  hibernate:
    dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
    format_sql: true
    use_sql_comments: true
    hbm2ddl:
      auto: update
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
    show_sql: true
    generate-ddl: true
  jackson:
    serialization:
      fail-on-empty-beans: false